name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # This specifies the operating system (Ubuntu)

    steps:
      - name: Check out code
        uses: actions/checkout@v3  # This checks out your code from the repository

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the version of Python you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies listed in requirements.txt

      - name: Run Python script
        run: python your_script.py  # Replace 'your_script.py' with your Python file
