name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Specify the operating system (Ubuntu)

    steps:
      - name: Check out code
        uses: actions/checkout@v3  # This checks out your code from the repository

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the version of Python you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies listed in requirements.txt

      - name: Install Flask
        run: pip install Flask  # Install Flask if not in requirements.txt

      - name: Run Flask app
        run: |
          nohup python your_script.py &  # Run Flask in the background (nohup prevents it from stopping)
          sleep 10  # Wait for Flask to start (this may vary depending on your system)

      - name: Test Flask app
        run: |
          curl http://127.0.0.1:5000/  # Test if Flask is running by making an HTTP request
